/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pl.polsl.vigenere.cipher;

import java.awt.event.ActionListener;
import java.util.Locale;
import javax.swing.*;

/**
 *
 * @author Bartosz Dera
 * Class implementing VigenereModel object
 */
public class VigenereView extends JFrame {

    /**
     * Creates new form VigenereView
     */
    public VigenereView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEncode = new javax.swing.JButton();
        jTextToCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextEncoded = new javax.swing.JTextArea();
        jTextKey = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonEncode.setText("Szyfruj");

        jLabel1.setText("Wiadomość do zaszyfrowania:");

        jLabel2.setText("Klucz (jeden znak):");

        jLabel3.setText("Wiadomość zaszyfrowana:");

        jTextEncoded.setColumns(20);
        jTextEncoded.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextEncoded.setRows(5);
        jTextEncoded.setWrapStyleWord(true);
        jTextEncoded.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextEncoded.setEnabled(false);
        jScrollPane1.setViewportView(jTextEncoded);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextKey, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jButtonEncode))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextToCode, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextToCode, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEncode)
                    .addComponent(jLabel2)
                    .addComponent(jTextKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEncode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextEncoded;
    private javax.swing.JTextField jTextKey;
    private javax.swing.JTextField jTextToCode;
    // End of variables declaration//GEN-END:variables

    /**
     * Getter of textToCode form textField
     * @return String object of textToCode
     */
    public String getTextToCode(){
       return jTextToCode.getText();
    }
    
    /**
     * Setter for textToCode field
     * @param text String to be set
     */
    public void setTextToCode(String text){
        jTextToCode.setText(text);
    }
    
    /**
     * Getter of secretLetter from textField
     * @return String object of secretLetter
     */
    public String getSecretLetter(){
        return jTextKey.getText().toUpperCase();
    }
    
    /**
     * Setter of secretLetter from textField
     * @param secretLetter String object of secretLetter
     */
    public void setSecretLetter(String secretLetter){
        jTextKey.setText(secretLetter);
    }
    
    /**
     * Setter of encodedMessage from VigenereModel
     * @param encodedText return value after encoding message
     */
    public void setEncodedMessage(String encodedText){
        SwingUtilities.invokeLater(                       //<----------- NIE WIEM JAK TO ZROBIC
               new Runnable(){
                   public void run(){
                    jTextEncoded.setText(encodedText);
                    }});
    }
    
    /**
     * Method adding listener of when the button was pressed
     * @param listenForEncodeButton Object of listenForEncodeButton
     */
    void addEncodeListener(ActionListener listenForEncodeButton){
        jButtonEncode.addActionListener(listenForEncodeButton);
    }
    
    /**
     * Method executing displaybox with information message
     * @param errorMessage String to be displayed
     */
    void displayErrorMessage(String errorMessage){
        JOptionPane.showMessageDialog(this, errorMessage);
    }
}
